spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    rest:
      uris: https://localhost:9200
      username: elastic
      password: ${ELASTIC_PASSWORD}
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        verification-mode: full
        trust-store-type: PKCS12
        trust-store: /usr/share/elasticsearch/config/www.projectkkk.pkcs12
        trust-store-password: ${CA_PASSWORD}
        key-store: classpath:www.projectkkk.com.pkcs12
        key-store-password: ${SPRINGBOOT_PASSWORD}
        key-store-type: PKCS12
  data:
    elasticsearch:
      repositories:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
  elasticsearch:
    rest:
      uris: https://elasticsearch:9200
      username: elastic
      password: ${ELASTIC_PASSWORD}
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        verification-mode: full
        trust-store-type: PKCS12
        trust-store: /usr/share/elasticsearch/config/www.projectkkk.pkcs12
        trust-store-password: ${CA_PASSWORD}
        key-store: classpath:www.projectkkk.com.pkcs12
        key-store-password: ${SPRINGBOOT_PASSWORD}
        key-store-type: PKCS12
  data:
    elasticsearch:
      repositories:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # 성능 최적화를 위해 false로 설정
  logging:
    level:
      org.springframework.data.elasticsearch.client.WIRE: TRACE
      org.springframework.data.elasticsearch: DEBUG
      org.elasticsearch: DEBUG

google:
  cloud:
    storage:
      credentials:
        json-key: "/usr/share/springboot/superb-analog-439512-g8-e7979f6854cd.json"

server:
  port: 443
  ssl:
    enabled: true
    verification-mode: full
    trust-store-type: PKCS12
    trust-store: /usr/share/elasticsearch/config/www.projectkkk.pkcs12
    trust-store-password: ${CA_PASSWORD}
    key-store: /app/www.projectkkk.pkcs12
    key-store-password: ${SPRINGBOOT_PASSWORD}
    key-store-type: PKCS12
    key-alias: www.projectkkk.com
  security:
    require-ssl: full
  hsts:
    enabled: false
